### ISSUE TITLE
npm install failed on windows 10

### ISSUE THREAD

**Issue by smartsoul** [expo/browser-polyfill#12]
I meet the error:
`find ../ -name .babelrc -delete

FIND: Parameter format not correct

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @expo/browser-polyfill@0.0.0-alpha.10 postinstall: `find ../ -name .babelrc -delete`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @expo/browser-polyfill@0.0.0-alpha.10 postinstall script.`

I install it on mac successfully.
Seems command 'find ../ -name .babelrc -delete' is broken.

**Comment by smartsoul** [comment]
OK. I find the solution, Install cygwin and add "C:\cygwin64\bin" to path.
It is not cool to meet the compatible issue.

**Comment by flybayer** [comment]
I also have this issue

**Comment by EvanBacon** [comment]
This find command has been removed for a bit. Please make sure you are running up-to-date versions. Duplicate #7
