### ISSUE TITLE
This breaks Firebase somehow

### ISSUE THREAD

**Issue by iameli** [expo/browser-polyfill#2]
Importing this package causes the Firebase JS library to not work. Currently diagnosing further.

**Comment by EvanBacon** [comment]
I was running into this bug too, but I added it the test app and couldn't recreate it. 
I've changed `EventEmitter` to `fb-emitter` and fixed some other minor bugs, I'm thinking that maybe these fixed it. `0.0.0-alpha.8` has the changes

**Comment by EvanBacon** [comment]
#5 possibly fixed, haven't tried every use case
