### ISSUE TITLE
Error: Unable to resolve module uuidv1 from 'uuid/v1';

### ISSUE THREAD

**Issue by BrandonBlanchard** [expo/browser-polyfill#41]
It looks like the import `import uuidv1 from 'uuid/v1';` in `browser-polyfill/src/DOM/HTMLImageElement.js` at ln6 isn't valid or a dependency was left out of your `package.json`.

I've been looking through the different uuid modules available on npm and none of them seem to fill this dependency. Could you provide a link to the correct module or update your `package.json`?

**Comment by BrandonBlanchard** [comment]
Looks like I might have found it, feel free to close this issue. Though you may want to add this to your package.json.
`https://www.npmjs.com/package/uuid/v/3.4.0`

**Comment by hanayashiki** [comment]
they are too busy to add a single dep
