### ISSUE TITLE
Command Failed error

### ISSUE THREAD

**Issue by lanzosuarez** [expo/browser-polyfill#7]
```
C:\Users\user\Documents\PONS FILES\WORK\JONATHAN\UOB-SUMMIT\node_modules\@expo\browser-polyfill: Command failed.
Exit code: 2
Command: find ../ -name .babelrc -delete
Arguments:
Directory: C:\Users\user\Documents\PONS FILES\WORK\JONATHAN\UOB-SUMMIT\node_modules\@expo\browser-polyfill


```

im installing expo-pixi but imgetting thiis error 

Environment
- "expo": "^29.0.0",
- "react": "16.3.1",
- "react-native": "https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz",
- node: 8.9.0
- yarn : 1.3.2

**Comment by EvanBacon** [comment]
Just pushed a new version. I don't have a windows computer to test on, so I just guessed at it.

**Comment by lanzosuarez** [comment]
Thanks man. I'll report back later :)

**Comment by EvanBacon** [comment]
You are still running the old version. Please make sure you update the module to `0.0.1-alpha.0`, delete your node_modules, and try again.
The command should be: https://github.com/expo/browser-polyfill/blob/e2d27866257da4d5fc8149243df7e78eaa66f4ef/package.json#L54

**Comment by lanzosuarez** [comment]
![image](https://user-images.githubusercontent.com/18522203/43448205-eac7b0d4-94df-11e8-9a68-daaa3604f1f7.png)

i think rm -rf doesnt work on windows :(

**Comment by lanzosuarez** [comment]
@EvanBacon i installed cgywin so i can run unix command on my machine. Thankss

**Comment by atavistock** [comment]
For me this is a breaking change resulting in:
```
error .../node_modules/@expo/browser-polyfill: Command failed.
Exit code: 127
Command: rimraf ../../gl-matrix/.babelrc
Arguments: 
Directory: .../node_modules/@expo/browser-polyfill
Output:
```

There is no `rimraf` executable in the path.  I was able to work around this by adding rimraf globally, which then made an executable in the path.

**Comment by EvanBacon** [comment]
Just pushed `0.1.0-alpha.1` working for me on OSX.
